[tool.poetry]
name = "alu-space"
version = "0.1.0"
description = ""
authors = ["Raasch"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.5"
python-dotenv = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
